# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ross Nelson
email: ross.nelson+github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.rnelson.me" # the base hostname & protocol for your site
twitter_username: rossnelson
github_username:  rnelson

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight