# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog
email: ross.nelson+github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  very infrequent posts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rnelson.github.io" # the base hostname & protocol for your site
github_username:  rnelson

theme: jekyll-theme-midnight
minima:
  skin: solarized-dark
  social_links:
    - { platform: bluesky, user_url: "https://bsky.app/profile/libexec.net" }
    - { platform: flickr, user_url: "https://flickr.com/photos/rossn/sets" }
    - { platform: github,  user_url: "https://github.com/rnelson" }
    - { platform: instagram,  user_url: "https://instagram.com/rossnelson84" }
    - { platform: mastodon,  user_url: "https://bsd.network/@rnelson" }

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [footnotes]
